import type { InboxAppearance } from "@novu/js/ui";

export const notificationAppearance: InboxAppearance = {
	variables: {
		colorBackground: "var(--color-surface-0)",
		colorForeground: "var(--color-text-primary)",
		colorPrimary: "var(--color-ink)",
		colorPrimaryForeground: "var(--primary-foreground)",
		colorSecondary: "var(--color-surface-2)",
		colorSecondaryForeground: "var(--color-text-primary)",
		colorCounter: "var(--color-danger)",
		colorCounterForeground: "var(--destructive-foreground)",
		colorNeutral: "var(--color-border)",
		colorShadow: "var(--shadow-premium)",
		colorRing: "var(--color-focus)",
		fontSize: "14px",
		borderRadius: "var(--radius-lg)",
		colorSeverityHigh: "var(--color-danger)",
		colorSeverityMedium: "var(--color-warning)",
		colorSeverityLow: "var(--color-info)",
	},
	elements: {
		root: { fontFamily: "Manrope, sans-serif" },
		inboxContent: { backgroundColor: "var(--color-surface-0)" },
		notificationListContainer: { padding: "12px", gap: "12px" },
		notificationList: { gap: "12px" },
		notification: {
			backgroundColor: "var(--color-surface-0)",
			border: "1px solid var(--color-border)",
			borderRadius: "var(--radius-lg)",
			boxShadow: "var(--shadow-xs)",
		},
		notificationBar: { backgroundColor: "var(--color-ink)", borderRadius: "9999px" },
		notificationSubject: { color: "var(--color-text-primary)", fontWeight: 600 },
		notificationBody: { color: "var(--color-text-secondary)" },
		notificationDate: { color: "var(--color-text-tertiary)", fontSize: "12px" },
		notificationDot: { backgroundColor: "var(--color-danger)" },
		notificationPrimaryAction__button: { backgroundColor: "var(--color-ink)", color: "var(--primary-foreground)", borderRadius: "var(--radius-md)" },
		notificationSecondaryAction__button: { backgroundColor: "var(--color-surface-2)", color: "var(--color-text-primary)", borderRadius: "var(--radius-md)" },
		notificationRead__button: { color: "var(--color-text-secondary)" },
		notificationArchive__button: { color: "var(--color-text-secondary)" },
		tabsList: { backgroundColor: "var(--color-surface-1)", borderBottom: "1px solid var(--color-border)", padding: "8px 12px" },
		tabsTrigger: { borderRadius: "var(--radius-full)", color: "var(--color-text-secondary)" },
		preferencesContainer: { padding: "12px" },
		scheduleContainer: { border: "1px solid var(--color-border)", borderRadius: "var(--radius-lg)", backgroundColor: "var(--color-surface-0)" },
	},
};
